language: node_js
node_js:
- '16'
services:
- mongodb
addons:
  code_climate:
    repo_token: 1dfca95f75f16185220d799289afce9e9dbfe6012484cdca0dbe5edc8c4fba74
notifications:
  email: false
  slack:
    rooms:
      secure: UY8q801ql+B6iVKTrfonnOjiMtkyXZbLuP5tYKuco/Dy5lEJzdZT2bdyVI2yT9acKfvf8AMdV4AEp4vnsBPlSXki4jM0IUpZ/VVWOBCcayPvJeBIASz4xCpzcRVP4lTNtIFOAQrcTsTeESzeOOcO0tkNgMqBnPg01xFo1lju+gCerEaJAZK5Rw30a+9NgZJVkULj5XmdvdZKG42C4hPWhrKOYlCilnBcOPdFF5r4MFTHXujgsoJvvltSoZnYahaw0P8ZqSVCV/Yni7UQcRjPg/NgGLBELcyO/1WAlMQIjq2k+BQZan8D/gXPe2OniNtQzm4/ZVonoImL5bFvtGkvjEkFq0kUa4X9fUj9ohk0KcqoTvd3jNAsAdduFwrgdYEa6Ztg5ZLCZBAA4DTZ82c0SIBlJtRT0NzxZcWTDz7E839ztMmjxKrawaUJ4xCYLHF9OQuvid2XJGA2ZST5YHCsztKxeuDcALFK5gbldGkU7VUxM6m6ZMSWQ0pY3JeOyC8w+CLz8oARU0vq/6K08qk2aE0TZmnpWdNgWZYEqsoR2yOumBUsb6isuqYj3jA8W1hms78ZyZtnDZ+3EE8TN1wdrFbfIldqLtJdMDasaW6T9v/Kj6D7q6IWLWAQtmUt0fN12LClI514mGvryU1rRq/1nlKR5IM7w23ZQxjgC3EAwL4=
    on_success: always
    on_failure: always
before_script:
- npm install -g codeclimate-test-reporter
after_script:
- codeclimate-test-reporter < coverage/lcov.info
