language: node_js
node_js:
- '16'
services:
- mongodb
addons:
  code_climate:
    repo_token: 5031ceee6955aff7d9006d42676460c00c8b05c131b21294d6526ac720c3d1ea
notifications:
  email: false
  slack:
    rooms:
      secure: f21SDzTB5N4SNN4ICmt545/SKaEcOi78TeSr58mLfu1W8xea1LD2krt6FvnWQFeAuA7DKvuNLVVVNxgll8fpbAENacALWuAkmK8dSAriMqvzTEsGlL+kUL/1kMvEp62SgjPeeReZEJfc7QF76H9u6JXZe1+SWwJFTea9H0Tt16LTaonTzMwrsolKhHMUjZMkd/ko9+eS098aR/1dJUw94lSfjeasDbSYcdpGyPhrgR8d+c51VK+xjqg4FcBWWqKeVRG6CqDln3KNZTlxViF7HJPdbWcWbg2DqJcWPhIhMqNeEGMk8Xv1M7CqKZG4Cm/qkuuGRldxw9qrNAEQmHeNifsuNwEWEPXts9Xk8Q40akF+XOS6z3qH5Ds5Q4K6hx+z3yx0JELHoAjO/2SwMKPtMMvcOsW9dN2DZ66JeVMIpoEsznkD09OWQ5KhAbYLFQ+e8WtsNuSEUZ20FCiqTi8VPUFnjTmQvnRSIcNGfFsMtwJPDao+6N475oOPgcEBMlwAEKKLS0dm1sxx+yQiQ8OLN5FSLHA8djcob1U//mwfko69XBBFp5Y2yuy7L+zHjxok8IGENauDQeyHC/TzInTU9d/EdPAPdcOLSBVW4SABKGBssyD4MZJEIiMZuJjbztscqHXJrbITRfkAJirusl17yW8xWd9BKmTqHb/9hCVNNqo=
    on_success: always
    on_failure: always
before_script:
- npm install -g codeclimate-test-reporter
after_script:
- codeclimate-test-reporter < coverage/lcov.info
