language: node_js
node_js:
- '16'
services:
- mongodb
addons:
  code_climate:
    repo_token: 1dfca95f75f16185220d799289afce9e9dbfe6012484cdca0dbe5edc8c4fba74
notifications:
  email: false
  slack:
    rooms:
      secure: d/015kxcGD6RPHzxJV16tmiAGlVu/w37Z6G6P6HDXQJmDPlU0zUuWK15Wdzc9/IzOJ8kiGXeoYjfp7SIBW94goN/xCfisbFG7xP032L2oBa0B1S7N8nHNcM9eiGbL3zH2Db9HtHCLFxDMjM5S0/ggXdtLlq/u1uvvU84epYDlBT/my0jUG6TXR12F6PAa24IJcHbDIxnswP2+yKF6bQlS3vAfpGnvkwI+mHhZzabrPc8aBIKSdNcZX26XdE7nLc3bB5+qbX9sXBpgFBEGkZG8xQ810JWF8r7NNTZpqDc8zI5KnA7xEwDcSfav0EpFMEq24GGGLNuSW+BKHZkwS7RZWjAh8n9PBfUP1O0Sqhjr1vKgwJZYVIfzxLHbNkFMwUYdz5jNXYT5eRkPViCwT+7GZpbLzsuz5EPTSQM4gVf1K39ZLd1C7TFH7eSMJxuBWD4IA6GgAxQhi9LqPawKtlTAqb50Bk8PwHQvfOfDD3IkFmpTKAH9g2o0nUGauzhjsagrEEOVlark+rJKcr/G7rO0zlWWHt191dAx9jH06H3BsIiKqyQ2lDpZXUKOW3D+l9jWPr61z0DSqiKWObvbVh6x25Gv1u0DAP2l5JLa0BdJvhQWgbovdTFZeINsPPTueZ+Ym/jncBrZ77LalWJZsEMjW3+K0X19IrhyJ0uzMhY4yY=
    on_success: always
    on_failure: always
before_script:
- npm install -g codeclimate-test-reporter
after_script:
- codeclimate-test-reporter < coverage/lcov.info
