language: node_js
node_js:
- '7'
- '8'
services:
- mongodb
addons:
  code_climate:
    repo_token: 93bb9a8e925e98f32f9f6bdd4cb7ee981b007fe629ac7bdc35281077d7a52f0a
notifications:
  email: false
  slack:
    rooms:
      secure: gavqMm+gvVjIHTX8mAElOPnoJh+rWKxITJWj7FVJnHwtxUzbVXDDzPk4ZFBgA3NJFrm+U4i7nIIB/gXnkn9EUFpi9LqQ3PGAyFth72c7V6Ab34r6XEyAT5m21HWjTHSWplmkaVTMGXJkHfl6y35bLTVAg19UcrOoRNNpCBVEiv8XBmf2xqEQI45QJH4GU+0RU7Vr8nqk+DKcoBNR6R9kRcPqpIRl3jIs110O09Whk5Mul8Ej0yDKgjss1cw17jWcf6fQn+NCM/ugLB7KZsr6UfEtpunpK/iU0a89VkkWv4LgC7ouCD/T+TfX72yXrbiVe5guUjHNYGcuET8rTijUL0mP5/1uy0A7zztzvGXqHI9IITZoil1hYj/COmbafTjovu8h5Zt2F3zeL5fV02iBzFY6MAY7xAuI8riMfuSH+C/fRop4CfHq21EFXmOzIn5q3ra24UYHav3w+mkgPoLjdxo3UAHoPrpemY4M0x6AK52MBin1LaWC+eCdFgMOeELmgSVPO4shcs3T/rARUPqKGDhBW94Oc6jyu/dk6iQ7rYpvzGI/ko88w1NsJYNreFLoL7ukJ+vryHgWPReUU2sDJUlBcP5Qz0MJrdTJFc0VtctrECJbxVehGx+3oEyLEQNqJFKi/RQNXuIlAsSZx6bWgAkTOQO7SJ7M2l2nHgvYZXo=
    on_success: always
    on_failure: always
before_script:
- npm install -g codeclimate-test-reporter
after_script:
- codeclimate-test-reporter < coverage/lcov.info
