language: node_js
node_js:
- '7'
- '8'
services:
- mongodb
addons:
  code_climate:
    repo_token: 93bb9a8e925e98f32f9f6bdd4cb7ee981b007fe629ac7bdc35281077d7a52f0a
notifications:
  email: false
  slack:
    rooms:
      secure: a57rs0/Cf/XPDjMkdByY0xMsu19dh59qIsvN2BloqHscUPFt3tvX06yRYu9ODbCUPgmtL7zSJ/TsS6IULp6IXZKg6tToqMFkLw7JZ8FEhfT//MmzwIMGK5HHhOvbqemAeBgwEtlH9/bw2n2AYaHGNapLMQonb8I5JQSpLKD8Y2qw3Awb9p4en9fu8i6K6il+StGHny+btYMVX9h3hTb8a5944l6qX/7KSrjisGin5UKjQxGzaHHjwPgtcJ9un0etca8g++a1iHEL4Kp7PfkBehmfhxmYjHYzkbMjQY+SeGUXEJv+hi4m3PCP0J+eusjeYpBjwo7GzlOjArNRWSeNBeTRVV8/fjhFiHqHaWqpm9V3As9/1qJhEkteZdl9w5WDbM3QkfD8v+33FlOH09FYhCazHAzN9d8GKH8wJX7onyphXwMdN+mn74iYWYWJvcyDD1yHJ9t0ZAXCyl9yCxEONtUahm/J9BrmLLf/GhZCJmlezE4GJS8Ull8VbRJtJ5DFGiT5LW1CAQGhII3HRdyclGjtLbvmtLC+c4hn+viY5ps2HmdMyOCY68oucQ4tsOj3q0YaMnX9OG2bKYG+XloEyComOp+vMWjCPtG+wQld2kzi82wjwi7YmxHjzVC3YL6ORrXdqCrY8wcbPP4MQYSgwsveTFl1gRybyBBz9xP48i8=
    on_success: always
    on_failure: always
before_script:
- npm install -g codeclimate-test-reporter
after_script:
- codeclimate-test-reporter < coverage/lcov.info
