language: node_js
node_js:
  - '7'
services:
  - mongodb
addons:
  apt:
    packages:
      - oracle-java8-set-default
  code_climate:
    repo_token: 'e112f5c3b1faeea91159d0f4176745addb2ceb254eb69d5ba4a53c2f06e19b25'
notifications:
  email: false
before_script:
  - export JAVA_HOME=/usr/lib/jvm/java-8-oracle
  - $JAVA_HOME/bin/java -version
  - npm install -g codeclimate-test-reporter
after_script:
  - codeclimate-test-reporter < coverage/lcov.info
