language: node_js
node_js:
  - '7'
  - '6'
addons:
  apt:
    packages:
      - oracle-java8-set-default
  code_climate:
    repo_token: '24778e356ae14ff57e6ec4e6fc1a4d615debebb841ddea0b3fb4a2f54e0840e9'
notifications:
  email: false
before_script:
  - export JAVA_HOME=/usr/lib/jvm/java-8-oracle
  - $JAVA_HOME/bin/java -version
  - npm install -g codeclimate-test-reporter
after_script:
  - cd /home/travis/build/weacast/weacast-grib2json/lib
  - $JAVA_HOME/bin/java -Xmx512M -jar grib2json-0.8.0-SNAPSHOT.jar /home/travis/build/weacast/weacast-grib2json/test/data/gfs.grib
  - codeclimate-test-reporter < coverage/lcov.info
